import random
from urllib.request import urlopen

FONTS_URL = {
    'https://github.com/impallari/Dosis/raw/master/fonts/v1007%20Fontlab%20-%20Original/TTF/Dosis-Bold.ttf',
    'https://github.com/impallari/Dosis/raw/master/fonts/v1007%20Fontlab%20-%20Original/TTF/Dosis-Book.ttf',
    'https://github.com/impallari/Dosis/raw/master/fonts/v1007%20Fontlab%20-%20Original/TTF/Dosis-ExtraBold.ttf',
    'https://github.com/impallari/Dosis/raw/master/fonts/v1007%20Fontlab%20-%20Original/TTF/Dosis-ExtraLight.ttf',
    'https://github.com/impallari/Dosis/raw/master/fonts/v1007%20Fontlab%20-%20Original/TTF/Dosis-Light.ttf',
    'https://github.com/impallari/Dosis/raw/master/fonts/v1007%20Fontlab%20-%20Original/TTF/Dosis-Medium.ttf',
    'https://github.com/impallari/Dosis/raw/master/fonts/v1007%20Fontlab%20-%20Original/TTF/Dosis-SemiBold.ttf',
    'https://github.com/googlefonts/roboto/raw/main/src/hinted/Roboto-Regular.ttf',
    'https://github.com/google/fonts/raw/main/ofl/lato/Lato-Regular.ttf',
    'https://github.com/ricochet-im/website/raw/master/static/fonts/Bree-Serif-regular/Bree-Serif-regular.ttf',
    'https://github.com/google/fonts/raw/main/ofl/cookie/Cookie-Regular.ttf',
    'https://github.com/cyrealtype/Lora-Cyrillic/raw/main/fonts/ttf/Lora-Bold.ttf',
    'https://github.com/cyrealtype/Lora-Cyrillic/raw/main/fonts/ttf/Lora-BoldItalic.ttf',
    'https://github.com/cyrealtype/Lora-Cyrillic/raw/main/fonts/ttf/Lora-Italic.ttf',
    'https://github.com/cyrealtype/Lora-Cyrillic/raw/main/fonts/ttf/Lora-Medium.ttf',
    'https://github.com/cyrealtype/Lora-Cyrillic/raw/main/fonts/ttf/Lora-MediumItalic.ttf',
    'https://github.com/cyrealtype/Lora-Cyrillic/raw/main/fonts/ttf/Lora-Regular.ttf',
    'https://github.com/cyrealtype/Lora-Cyrillic/raw/main/fonts/ttf/Lora-SemiBold.ttf',
    'https://github.com/cyrealtype/Lora-Cyrillic/raw/main/fonts/ttf/Lora-SemiBoldItalic.ttf',
    'https://github.com/googlefonts/opensans/raw/main/fonts/ttf/OpenSans-Bold.ttf',
    'https://github.com/googlefonts/opensans/raw/main/fonts/ttf/OpenSans-BoldItalic.ttf',
    'https://github.com/googlefonts/opensans/raw/main/fonts/ttf/OpenSans-CondensedBold.ttf',
    'https://github.com/googlefonts/opensans/raw/main/fonts/ttf/OpenSans-CondensedBoldItalic.ttf',
    'https://github.com/googlefonts/opensans/raw/main/fonts/ttf/OpenSans-CondensedExtraBold.ttf',
    'https://github.com/googlefonts/opensans/raw/main/fonts/ttf/OpenSans-CondensedExtraBoldItalic.ttf',
    'https://github.com/googlefonts/opensans/raw/main/fonts/ttf/OpenSans-CondensedItalic.ttf',
    'https://github.com/googlefonts/opensans/raw/main/fonts/ttf/OpenSans-CondensedLight.ttf',
    'https://github.com/googlefonts/opensans/raw/main/fonts/ttf/OpenSans-CondensedLightItalic.ttf',
    'https://github.com/googlefonts/opensans/raw/main/fonts/ttf/OpenSans-CondensedRegular.ttf',
    'https://github.com/googlefonts/opensans/raw/main/fonts/ttf/OpenSans-CondensedSemiBold.ttf',
    'https://github.com/googlefonts/opensans/raw/main/fonts/ttf/OpenSans-CondensedSemiBoldItalic.ttf',
    'https://github.com/googlefonts/opensans/raw/main/fonts/ttf/OpenSans-ExtraBold.ttf',
    'https://github.com/googlefonts/opensans/raw/main/fonts/ttf/OpenSans-ExtraBoldItalic.ttf',
    'https://github.com/googlefonts/opensans/raw/main/fonts/ttf/OpenSans-Italic.ttf',
    'https://github.com/googlefonts/opensans/raw/main/fonts/ttf/OpenSans-Light.ttf',
    'https://github.com/googlefonts/opensans/raw/main/fonts/ttf/OpenSans-LightItalic.ttf',
    'https://github.com/googlefonts/opensans/raw/main/fonts/ttf/OpenSans-Regular.ttf',
    'https://github.com/googlefonts/opensans/raw/main/fonts/ttf/OpenSans-SemiBold.ttf',
    'https://github.com/googlefonts/opensans/raw/main/fonts/ttf/OpenSans-SemiBoldItalic.ttf',
    'https://github.com/vernnobile/OswaldFont/raw/master/3.0/Italic/800/Oswald-HeavyItalic.ttf',
    'https://github.com/vernnobile/OswaldFont/raw/master/3.0/Italic/700/Oswald-BoldItalic.ttf',
    'https://github.com/vernnobile/OswaldFont/raw/master/3.0/Italic/600/Oswald-Demi-BoldItalic.ttf',
    'https://github.com/vernnobile/OswaldFont/raw/master/3.0/Italic/500/Oswald-MediumItalic.ttf',
    'https://github.com/vernnobile/OswaldFont/raw/master/3.0/Italic/400/Oswald-RegularItalic.ttf',
    'https://github.com/vernnobile/OswaldFont/raw/master/3.0/Italic/300/Oswald-LightItalic.ttf',
    'https://github.com/vernnobile/OswaldFont/raw/master/3.0/Italic/200/Oswald-Extra-LightItalic.ttf',
    'https://github.com/vernnobile/OswaldFont/raw/master/3.0/Roman/800/Oswald-Heavy.ttf',
    'https://github.com/vernnobile/OswaldFont/raw/master/3.0/Roman/700/Oswald-Bold.ttf',
    'https://github.com/vernnobile/OswaldFont/raw/master/3.0/Roman/600/Oswald-DemiBold.ttf',
    'https://github.com/vernnobile/OswaldFont/raw/master/3.0/Roman/500/Oswald-Medium.ttf',
    'https://github.com/vernnobile/OswaldFont/raw/master/3.0/Roman/400/Oswald-Regular.ttf',
    'https://github.com/vernnobile/OswaldFont/raw/master/3.0/Roman/300/Oswald-Light.ttf',
    'https://github.com/vernnobile/OswaldFont/raw/master/3.0/Roman/200/Oswald-ExtraLight.ttf',
    'https://github.com/adobe-fonts/source-sans/raw/release/TTF/SourceSans3-Black.ttf',
    'https://github.com/adobe-fonts/source-sans/raw/release/TTF/SourceSans3-BlackIt.ttf',
    'https://github.com/adobe-fonts/source-sans/raw/release/TTF/SourceSans3-Bold.ttf',
    'https://github.com/adobe-fonts/source-sans/raw/release/TTF/SourceSans3-BoldIt.ttf',
    'https://github.com/adobe-fonts/source-sans/raw/release/TTF/SourceSans3-ExtraLight.ttf',
    'https://github.com/adobe-fonts/source-sans/raw/release/TTF/SourceSans3-ExtraLightIt.ttf',
    'https://github.com/adobe-fonts/source-sans/raw/release/TTF/SourceSans3-It.ttf',
    'https://github.com/adobe-fonts/source-sans/raw/release/TTF/SourceSans3-Light.ttf',
    'https://github.com/adobe-fonts/source-sans/raw/release/TTF/SourceSans3-LightIt.ttf',
    'https://github.com/adobe-fonts/source-sans/raw/release/TTF/SourceSans3-Medium.ttf',
    'https://github.com/adobe-fonts/source-sans/raw/release/TTF/SourceSans3-MediumIt.ttf',
    'https://github.com/adobe-fonts/source-sans/raw/release/TTF/SourceSans3-Regular.ttf',
    'https://github.com/adobe-fonts/source-sans/raw/release/TTF/SourceSans3-Semibold.ttf',
    'https://github.com/adobe-fonts/source-sans/raw/release/TTF/SourceSans3-SemiboldIt.ttf',
    'https://github.com/mozilla/Fira/raw/master/ttf/FiraMono-Bold.ttf',
    'https://github.com/mozilla/Fira/raw/master/ttf/FiraMono-Medium.ttf',
    'https://github.com/mozilla/Fira/raw/master/ttf/FiraMono-Regular.ttf',
    'https://github.com/mozilla/Fira/raw/master/ttf/FiraSans-Bold.ttf',
    'https://github.com/mozilla/Fira/raw/master/ttf/FiraSans-BoldItalic.ttf',
    'https://github.com/mozilla/Fira/raw/master/ttf/FiraSans-Book.ttf',
    'https://github.com/mozilla/Fira/raw/master/ttf/FiraSans-BookItalic.ttf',
    'https://github.com/mozilla/Fira/raw/master/ttf/FiraSans-Eight.ttf',
    'https://github.com/mozilla/Fira/raw/master/ttf/FiraSans-EightItalic.ttf',
    'https://github.com/mozilla/Fira/raw/master/ttf/FiraSans-ExtraBold.ttf',
    'https://github.com/mozilla/Fira/raw/master/ttf/FiraSans-ExtraBoldItalic.ttf',
    'https://github.com/mozilla/Fira/raw/master/ttf/FiraSans-ExtraLight.ttf',
    'https://github.com/mozilla/Fira/raw/master/ttf/FiraSans-ExtraLightItalic.ttf',
    'https://github.com/mozilla/Fira/raw/master/ttf/FiraSans-Four.ttf',
    'https://github.com/mozilla/Fira/raw/master/ttf/FiraSans-FourItalic.ttf',
    'https://github.com/mozilla/Fira/raw/master/ttf/FiraSans-Hair.ttf',
    'https://github.com/mozilla/Fira/raw/master/ttf/FiraSans-HairItalic.ttf',
    'https://github.com/mozilla/Fira/raw/master/ttf/FiraSans-Heavy.ttf',
    'https://github.com/mozilla/Fira/raw/master/ttf/FiraSans-HeavyItalic.ttf',
    'https://github.com/mozilla/Fira/raw/master/ttf/FiraSans-Italic.ttf',
    'https://github.com/mozilla/Fira/raw/master/ttf/FiraSans-Light.ttf',
    'https://github.com/mozilla/Fira/raw/master/ttf/FiraSans-LightItalic.ttf',
    'https://github.com/mozilla/Fira/raw/master/ttf/FiraSans-Medium.ttf',
    'https://github.com/mozilla/Fira/raw/master/ttf/FiraSans-MediumItalic.ttf',
    'https://github.com/mozilla/Fira/raw/master/ttf/FiraSans-Regular.ttf',
    'https://github.com/mozilla/Fira/raw/master/ttf/FiraSans-SemiBold.ttf',
    'https://github.com/mozilla/Fira/raw/master/ttf/FiraSans-SemiBoldItalic.ttf',
    'https://github.com/mozilla/Fira/raw/master/ttf/FiraSans-Thin.ttf',
    'https://github.com/mozilla/Fira/raw/master/ttf/FiraSans-ThinItalic.ttf',
    'https://github.com/mozilla/Fira/raw/master/ttf/FiraSans-Two.ttf',
    'https://github.com/mozilla/Fira/raw/master/ttf/FiraSans-TwoItalic.ttf',
    'https://github.com/mozilla/Fira/raw/master/ttf/FiraSans-Ultra.ttf',
    'https://github.com/mozilla/Fira/raw/master/ttf/FiraSans-UltraItalic.ttf',
    'https://github.com/mozilla/Fira/raw/master/ttf/FiraSans-UltraLight.ttf',
    'https://github.com/mozilla/Fira/raw/master/ttf/FiraSans-UltraLightItalic.ttf',
}

CACHED_FONTS = {}


def get_font_as_bytes():
    font_as_bytes = None
    while font_as_bytes is None:
        font_url = random.choice(FONTS_URL)
        try:
            font_as_bytes = CACHED_FONTS.setdefault(font_url, urlopen(font_url).read())
        except Exception as e:
            print(f"Error al obtener la fuente {font_url}: {e}")

    return font_as_bytes
